### ISSUE TITLE
Check Yamamura at normal incidence 

### ISSUE THREAD

**Issue by dcurreli** [lcpp-org/PlasmaEDU#11]
Check the following implementation of Yamamura's sputtering yields at normal incidence against published values.

**Comment by Huq2090** [comment]
The following slides include verification of sputtering yield for normal incidence.
[sputtering_yield_for_normal_incidence.pdf](https://github.com/lcpp-org/PlasmaEDU/files/10744148/sputtering_yield_for_normal_incidence.pdf)

**Comment by dcurreli** [comment]
Excellent
